spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: spring_cloud_user
      password: '1234'

twitter-to-kafka-service:
  enable-mock-tweets: true
encrypt:
  key: ${MICROSERVICES_ENCRYPT_KEY}