server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Herickwill/spring-cloud-config-server-repository
          username:
          password:
          clone-on-start: true
          try-master-branch: on
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '1234'